MODEL:
  NUM_CLASSES: 21
  BACKBONE:
    NAME: 'resnet50_fpn'
    OUT_CHANNELS: (256, 256, 256, 256, 256)
  PRIORS:
    FEATURE_MAPS: [32, 16, 8, 4, 2]
    STRIDES: [8, 24, 64, 128, 256]
    MIN_SIZES: [21, 45, 99, 153, 207, 236]
    MAX_SIZES: [45, 99, 153, 207, 236, 270]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: 256
DATASETS:
  TRAIN: ("voc_2012_train", )
  TEST: ("voc_2012_val", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 4
  LR: 1e-4

OUTPUT_DIR: 'outputs/resnet50-fpn-voc'
